add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$java\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
